# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afb44d41321add710e2dff4657892ac1b87734f655c2279cf774cade7ae391fb2516b66269bfb7ec4b31b8936a1bc57dea5deb18aa2ae2ace5d76df0d0dc159

test:
  secret_key_base: edb768df52e60cddd8968bbe3e7e0bd5c5d9859866b5b28210bf2e3125ef171b10370a6bd2331a6d7ec1780bf09d8830027da33d261688786c4855af8f9bc095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
